using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PointBlank.Core.Models.Enums
{
    [Flags]
    public enum MapIdEnum
    {
        PortAkaba = 1,
        Redrock = 2,
        Library = 3,
        MStation = 4,
        MidnightZone = 5,
        Uptown = 6,
        BurningHall = 7,
        DSquad = 8,
        Crackdown = 9,
        SaintMansion = 10,
        EasternRoad = 11,
        Downtown = 12,
        LuxVille = 13,
        Blowcity = 14,
        Stormtube = 15,
        Giran2 = 16,
        BreakDown = 17,
        TrainingCamp = 18,
        Sentrybase = 19,
        DesertCamp = 20,
        Kickpoint = 21,
        FaceRock = 22,
        SupplyBase = 23,
        SandStorm = 24,
        ShoppingCenter = 25,
        Safari = 26,
        DragonAlley = 27,
        MachuPichu = 28,
        Twotowers = 29,
        AngkorRuins = 30,
        GhostTown = 31,
        GrandBazaar = 32,
        Under23 = 33,
        TaipeiCityMall = 34,
        Safari2 = 35,
        Metro = 36,
        RushHour = 37,
        CargoPort = 38,
        BlackMamba = 39,
        Holiday = 40,
        WestStation = 41,
        HouseMuseum = 42,
        Outpost = 43,
        Hospital = 44,
        Downtown2 = 45,
        Cargoship = 46,
        Airport = 47,
        SafeHouse = 48,
        Hardrock = 49,
        Giran = 50,
        Helispot = 51,
        BlackPanther = 52,
        BreedingNest = 53,
        D_Uptown = 54,
        D_BreakDown = 55,
        DinoLab = 56,
        Tutorial = 57,
        WaterComplex = 65,
        HotelCamouflage = 66,
        PumpkinHollow = 67,
        TestMap = 68,
        BattleShip = 69,
        RampartTown = 70,
        Ballistic = 71,
        Test = 72,
        Holiday2 = 73,
        RothenVillage = 74,
        MerryWhiteVillage = 75,
        FalluCity = 76,
        Hindrance = 77,
        Sewerage = 78,
        SlumArea = 79,
        New_Library = 80,
        C_Sandstorm = 81,
        DinoRuins = 82,
        FatalZone = 83,
        MarineWave = 84,
        StillRaid = 85,
        OldDock = 86,
        BioLab = 87,
        BrokenAlley = 88,
        BankHall = 89,
        Provence = 91,
        MBridge = 92,
        Mihawk = 93,
        DesertCanyon = 94,
        AmperaBridge = 95,
        S_Twotowers = 96,
        ThaiStadium = 97,
        FortSantiago = 98,
        Roadside = 99,
        F_Uptown = 100,
        InfectionAirport = 101,
        BlowCity = 102,
        KhodsanRoad = 103,
        SpacePort = 104,
        Junkyard = 105,
        DrainTunnel = 108,
    }
}
